### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by mercuriete** [mercuriete/android-musician-tools#1]
### Product Backlog
Here we can discuss the product backlog before create a new feature request and before add it to the
[kanban board](https://github.com/mercuriete/android-musician-tools/projects/1)

**Functional requirements**
- [x] BPM Detector with a button #2 #3 
- [x] add bottom navigation #12 #15
- [ ] add settings + permission fragment
- [ ] Permission manager (request to user app's permissions) (record audio at least)
- [ ] Metronome without accentuation (only tempo) (tic tic tic)
- [ ] Metronome with accentuation (tempo + flexible time signature) (tic toc toc toc)
- [ ] Pitch Detector (harmonic product spectrum) (Equal temperament)
- [ ] BPM Detector with a sound (clap clap clap)

**Non functional requirements**
- [x] Continous Integration with Travis CI 90bcae12bf21bf6da07149dc633954f7e8ed74c9
- [x] Unit Testing #2 #3
- [x] Clean Boilerplate from skeleton #6 #7 
- [x] Dependency Injection Framework (Dagger2) #4 #5
- [x] Add editorconfig #10 #11
- [x] MVP Architecture #8 #9
- [x] Learn and Use fragments #13 #14
- [x] update android sdk to 29.0.0 #18 #19
- [x] Jacoco reports #20 #21 #22
- [x] Update deps 2020-05 #27 #28
- [x] Automatic Version Bump #29 #30
- [x] Azure Pipelines only build #36 #37
- [x] Add Mailmap #39 #40
- [x] Update deps 2020-06 #33 #34
- [x] Espresso Testing + cucumber #25 #26
- [x] Implement github actions CI #68 #69
- [x] Instrumented test in CI #94 #95
- [x] Migrate from dagger2 to hilt #102 #103
- [x] Sonarcloud.io #20 #21 #22 #46 #116
- [x] Send Jacoco report to sonar #23 #24 #46 #116 #122
- [ ] Azure Pipelines sign
- [ ] Azure Pipelines upload to Google Play
- [ ] App Translated to all languages (en_US, en_GB, es_ES at least)
- [ ] Interface should be beautiful
- [ ] Continous Deployment to Google Play
- [ ] Clean Code
- [ ] Fast and Performant code
- [ ] Usage of GPU for audio processing (Vulkan Compute Shaders) (this is kind a joke or wishlist)
- [ ] I wanna be rich
